### ISSUE TITLE
The fastpack installation issue

### ISSUE THREAD

**Issue by I-FAN** [Dynatrace/Dynatrace-hybris-eCommerce-Fastpack#5] opened 2019-05-17 02:55 UTC
Dear Sir, 

I met a problem after I executed the dynatrace_hybris_ecommerce_fastpack.py. 
![image_2019_05_14T09_46_29_291Z-1](https://user-images.githubusercontent.com/8671922/57898898-7cbd1880-788d-11e9-91fe-14c79d6c325d.png)

I entered API token. Then It asked me to Enter your Tenant URL(example: foo.live.dynatrace.com). However, it came out a error message, 'utr808' is not defined. 
"utr808" is our tenent name.

![IMG_7139](https://user-images.githubusercontent.com/8671922/57899412-88a9da00-788f-11e9-97f9-e534a265f6ca.PNG)

Could you help me to figure it out?

Thank you.

**Comment by Dynatrace-BrianWilson** [comment] 2019-05-31 14:56
sorry, I didn't get notification on this. I will take a look.

**Comment by Dynatrace-BrianWilson** [comment] 2019-05-31 15:21
I tried your tenant name utr808.dynatrace-managed.com with a fake API Token, and the script had no problem with the tenantID.  If obviously failed in trying to make a connection, but in your instance, you script is failing at line 289 which is way before the connection is tested. 289 is where your input is assigned to:
`dtTenantURL += getdtTenantURL()`

Are you running this with Python 3?  It was written for Python 3. I have no idea what might break if you're using python 2.x

Since I cannot reproduce the error, I'll offer a workaround. 

in the script, 
comment out line 22
`dtTenantURL = 'https://'`

comment out lines 59 - 70
`def getdtTenantURL():`
`    """ this function gets the Tenant URL, validates it's not empty, and returns it to the dtTenantURL variable"""`
`    dtTenantURL = input('Enter your Tenant URL (example: foo.live.dynatrace.com): ')`
`    if len(dtTenantURL) > 0:`
`        return dtTenantURL`
`    else:`
`        dtTenantURL = input('Please enter your Tenant URL. You cannot proceed without it (example: foo.live.dynatrace.com): ')`
`        if len(dtTenantURL) < 1:`
`            print('Please obtain a Tenant URL before proceeding (example: foo.live.dynatrace.com).')`
`            logging.error(' Tenant URL Error: expecting an input of more than 1 character')`
`            exit(1)`
`        return dtTenantURL`

Then, on line 289, change it to
`dtTenantURL = 'https://utr808.dynatrace-managed.com`

this will set hard code the tenant in the script.

**Comment by I-FAN** [comment] 2019-06-14 05:38
Dear Brian, 

My customer tried this hard code. He use Python 3.6.8. 
After changed on line 289, it came out a 404 error !!!!!!!????

<img width="401" alt="Screen Shot 2019-06-14 at 13 36 55" src="https://user-images.githubusercontent.com/8671922/59485744-8f853600-8ea9-11e9-964b-40360f55eaa7.png">


We have no clue what next we are going to do. 
Please give us some advise.

Sincerely, 

I-Fan

**Comment by Dynatrace-BrianWilson** [comment] 2019-06-14 15:52
can you give me your python script so I can check it over?  Does anybody know Python over there that might be able to do additional debugging?

**Comment by Dynatrace-BrianWilson** [comment] 2019-06-14 16:59
404 means not found. is the utr808 URL accessible from the desktop the python script is running from?

**Comment by I-FAN** [comment] 2019-06-17 06:50
Dear Brian,

You can see the attachment below. I believe the utr808 URL is accessible.

![Screen Shot 2019-06-17 at 14 47 21](https://user-images.githubusercontent.com/8671922/59583776-e3dd1f80-910e-11e9-8230-61ff80655174.png)


Anything else that I can try for you to get more information to clarify this issue?


PS: They use python3 for script and version 6.6 for Hybris

Sincerely, 

I-Fan

**Comment by Dynatrace-BrianWilson** [comment] 2019-06-18 14:44
please send me your python code. 
If possible, send me a temp API token. email it to brian dot wilson at dynatrace dot com

**Comment by I-FAN** [comment] 2019-06-19 03:21
Dear Biran, 

Cindy, my colleague has just sent the temp API token and .py file to you.
![image_2019_06_19T01_54_36_894Z](https://user-images.githubusercontent.com/8671922/59734515-4dcb0580-9284-11e9-98a1-8506aadd5034.png)

The above is the only row that we changed.

Thank you

 
Sincerely, 

I-Fan

**Comment by Dynatrace-BrianWilson** [comment] 2019-06-19 16:59
this issue is accessibility on your end. I could make the connection when using the internal managed instance address, but not with the utr808 address.  Also, for a managed instance, the environment has to be included.  I'll send the details of what worked for me to your colleague and you can figure it out from there.

**Closed as completed by Dynatrace-BrianWilson** 2019-06-19 16:59 UTC
